config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users
    get "reservations/top", to: "reservations#top"
    get "reservations/confirm", to: "reservations#confirm"
    resources :reservations
  end

  namespace :admin do
    root to: "stocks#index"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :dealers do
      member do
        get "new_station"
        post "create_station"
        get "new_car"
        post "create_car"
      end
    end
    resources :stations
    resources :cars
    resources :stocks
  end
end

app/models/dealer.rb
class Dealer < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :login_id, presence: true, uniqueness: true

  has_many :stations
  has_many :cars
end

app/controllers/admin/dealers_controller.rb
class Admin::DealersController < ApplicationController
  layout "admin/stocks"

  def new
    @dealer = Dealer.new
  end

  def create
    @dealer = Dealer.new(dealer_params)

    if @dealer.save
      redirect_to admin_dealers_path, notice: "ディーラー「#{@dealer.name}」を登録しました"
    else
      render :new
    end
  end

  def edit
    @dealer = Dealer.find(params[:id])
  end

  def show
    @dealer = Dealer.find(params[:id])
  end

  def index
    @dealers = Dealer.all
  end

  def update
    @dealer = Dealer.find(params[:id])

    if @dealer.update(dealer_params)
      redirect_to admin_dealers_path, notice: "ディーラー「#{@dealer.name}」を更新しました"
    else
      render :new
    end
  end

  def destroy
    @dealer = Dealer.find(params[:id])
    @dealer.destroy
    redirect_to admin_dealers_url, notice: "ディーラー「#{@dealer.name}」を削除しました"
  end

  def new_station
    @station = Station.new
  end

  def create_station
    dealer = Dealer.find(params[:id])
    @station = dealer.stations.new(station_params)

    if @station.save
      redirect_to admin_stations_path, notice: "「#{@station.name}」駅を登録しました"
    else
      render :new
    end
  end

  def new_car
    @car = Car.new
  end

  def create_car
    dealer = Dealer.find(params[:id])
    @car = dealer.cars.new(car_params)
    if @car.save
      redirect_to admin_cars_path, notice: "「#{@car.name}」を登録しました"
    else
      Rails.logger.debug(@car.errors.messages)
      render :new
    end
  end


  private

  def dealer_params
    params.require(:dealer).permit(:name, :login_id, :password, :password_confirmation)
  end

  def station_params
    params.require(:station).permit(:name, :waiting_spot, :map_image)
  end

  def car_params
    params.require(:car).permit(:name, :count, :car_image)
  end

end

app/helpers/admin/dealers_helper.rb
module Admin::DealersHelper
end

app/views/admin/dealers/_car_form.html.erb
<%= form_for(car, url: {controller: "dealers", action: "create_car"}) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :count %>
    <%= f.text_field :count, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :car_image %>
    <%= f.file_field :car_image, id: :car_image%>
  </div>

  <%= f.submit "登録する", class: "btn btn-primary" %>
<% end %>

app/views/admin/dealers/_form.html.erb
<%= form_with model: [:admin, dealer], local: true do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :login_id %>
    <%= f.text_field :login_id, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>

  <%= f.submit "登録する", class: "btn btn-primary" %>
<% end %>

app/views/admin/dealers/_station_form.html.erb
<%= form_for(station, url: {controller: "dealers", action: "create_station"}) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :waiting_spot %>
    <%= f.text_field :waiting_spot, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :map_image %>
    <%= f.file_field :map_image %>
  </div>

  <%= f.submit "登録する", class: "btn btn-danger" %>
<% end %>

app/views/admin/dealers/edit.html.erb
<h1>ディーラーの店舗編集</h1>

<nav class = "justify-content-end">
  <%= link_to "一覧", admin_dealers_path, class: "nav-link" %>
</nav>

<%= render partial: "form", locals: {dealer: @dealer} %>

app/views/admin/dealers/index.html.erb
<div class="admin-wrapper">
  <div class="container admin-container">

    <h1>登録ディーラー一覧</h1>

    <%= link_to "新規登録", new_admin_dealer_path, class: "btn btn-secondary btn-admin" %>

    <table class = "table table-hover">
      <thead class = thead-default>
        <tr>
          <th><%= Dealer.human_attribute_name(:id) %></th>
          <th><%= Dealer.human_attribute_name(:name) %></th>
          <th>ディーラー情報</th>
          <th>駅の情報</th>
          <th>試乗車の情報</th>
        </tr>
      </thead>
      <tbody>
        <% @dealers.each do |dealer| %>
          <tr>
            <td><%= dealer.id %></td>
            <td><%= dealer.name %></td>
            <td>
              <%= link_to "編集", edit_admin_dealer_path(id: dealer.id), class: "btn btn-primary mr-3" %>
              <%= link_to "削除", admin_dealer_path(id: dealer.id), method: :delete, data: {confirm: "ディーラー「#{dealer.name}」を削除します。よろしいですか？"}, class: "btn btn-danger mr-3" %>
            </td>
            <td>
              <%= link_to "登録", new_station_admin_dealer_path(id: dealer.id), class: "btn btn-primary mr-3" %>
            </td>
            <td>
              <%= link_to "登録", new_car_admin_dealer_path(id: dealer.id), class: "btn btn-primary mr-3" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/admin/dealers/new.html.erb
<div class="admin-wrapper">
  <div class="container admin-container">


    <h1>ディーラーの店舗登録</h1>

    <%= link_to "店舗一覧", admin_dealers_path, class: "btn btn-secondary btn-admin" %>
    <%= render partial: "form", locals: {dealer: @dealer} %>

  </div>
</div>

app/views/admin/dealers/new_car.html.erb
<div class="admin-wrapper">
  <div class="container admin-container">

    <h1>試乗車の登録</h1>

    <%= link_to "試乗車一覧", admin_cars_path, class: "btn btn-secondary btn-admin" %>
    <%= render partial: "car_form", locals: {car: @car} %>
  </div>
</div>

app/views/admin/dealers/new_station.erb
<div class="admin-wrapper">
  <div class="container admin-container">

    <h1>駅情報の登録</h1>

    <%= link_to "駅一覧", admin_stations_path, class: "btn btn-secondary btn-admin" %>
    <%= render partial: "station_form", locals: {station: @station} %>
  </div>
</div>

app/views/admin/dealers/show.html.erb
<h1>Admin::Dealers#show</h1>
<p>Find me in app/views/admin/dealers/show.html.erb</p>