config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users
    get "reservations/top", to: "reservations#top"
    get "reservations/confirm", to: "reservations#confirm"
    resources :reservations
  end

  namespace :admin do
    root to: "stocks#index"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :dealers do
      member do
        get "new_station"
        post "create_station"
        get "new_car"
        post "create_car"
      end
    end
    resources :stations
    resources :cars
    resources :stocks
  end
end

app/models/station.rb
class Station < ApplicationRecord
  validates :name, presence: true
  validates :waiting_spot, presence: true
  validates :map_image, presence: true
  validates :dealer_id, presence: true

  belongs_to :dealer

  mount_uploader :map_image, ImageUploader
end

app/controllers/admin/stations_controller.rb
class Admin::StationsController < ApplicationController
  layout "admin/stocks"

  #def new
  #  @station = Station.new
  #end

  #def create
  #  dealer = Dealer.find(params[:id])
  #  @station = dealer.stations.new(station_params)
  #    if @station.save
  #      redirect_to admin_stations_path, notice: "「#{@station.name}」駅を登録しました"
  #    else
  #      render :new
  #    end
  #end

  def edit
    @station = Station.find(params[:id])
  end

  def show
    @station = Station.find(params[:id])
  end

  def index
    @stations = Station.all
  end

  def update
    @station = Station.find(params[:id])

    if @station.update(station_params)
      redirect_to admin_stations_path, notice: "「#{@station.name}」駅を更新しました"
    else
      render :new
    end
  end

  def destroy
    @station = Station.find(params[:id])
    @station.destroy
    redirect_to admin_stations_url, notice: "「#{@station.name}」駅を削除しました"
  end


  private

  def station_params
    params.require(:station).permit(:name, :waiting_spot, :map_image)
  end

end

app/helpers/admin/stations_helper.rb
module Admin::StationsHelper
end

app/views/admin/stations/_form.html.erb
<%= form_with model: [:admin, station], local: true do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :waiting_spot %>
    <%= f.text_field :waiting_spot, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :map_image %>
    <%= f.file_field :map_image %>
  </div>

  <%= f.submit "登録する", class: "btn btn-primary" %>
<% end %>

app/views/admin/stations/edit.html.erb
<div class="admin-wrapper">
  <div class="container admin-container">

    <h1>駅情報の編集</h1>

    <nav class = "justify-content-end">
      <%= link_to "一覧", admin_stations_path, class: "nav-link" %>
    </nav>

    <%= render partial: "form", locals: {station: @station} %>

  </div>
</div>

app/views/admin/stations/index.html.erb
<div class="admin-wrapper">
  <div class="container admin-container">

    <h1>ユーザーとの待ち合わせ場所</h1>

    <%#<%= link_to "新規登録", new_admin_station_path, class: "btn btn-primary btn-admin" %>

    <table class = "table table-hover">
      <thead class = thead-default>
        <tr>
          <th><%= Station.human_attribute_name(:name) %></th>
          <th><%= Station.human_attribute_name(:waiting_spot) %></th>
          <th><%= Station.human_attribute_name(:map_image) %></th>
          <th><%= Station.human_attribute_name(:dealer_id) %></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @stations.each do |station| %>
          <tr>
            <td><%= station.name %></td>
            <td><%= station.waiting_spot %></td>
            <td><%= image_tag station.map_image.url %></td>
            <td><%= station.dealer_id %></td>
            <td>
              <%= link_to "編集", edit_admin_station_path(id: station.id), class: "btn btn-primary mr-3" %>
              <%= link_to "削除", admin_station_path(id: station.id), method: :delete, data: {confirm: "「#{station.name}」駅を削除します。よろしいですか？"}, class: "btn btn-danger mr-3" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/stations/new.html.erb
<h1>駅情報の登録</h1>

<nav class = "justify-content-end">
  <%= link_to "一覧", admin_stations_path, class: "nav-link" %>
</nav>

<%= render partial: "form", locals: {station: @station} %>

app/views/admin/stations/show.html.erb
<h1>Admin::Stations#show</h1>
<p>Find me in app/views/admin/stations/show.html.erb</p>