config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users
    get "reservations/top", to: "reservations#top"
    get "reservations/confirm", to: "reservations#confirm"
    resources :reservations
  end

  namespace :admin do
    root to: "stocks#index"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :dealers do
      member do
        get "new_station"
        post "create_station"
        get "new_car"
        post "create_car"
      end
    end
    resources :stations
    resources :cars
    resources :stocks
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test Drive</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color:#002698">
      <div class="container">
        <span style="font-family: cursive" >
          <%= link_to "Test Drive", public_reservations_top_path, class: "navbar-brand text-white" %>
        </span>
        <ul class="nav navbar-nav navbar-right navbar-collapse collapse ml-auto">
          <% if current_user %>
            <li class="nav-item"><%= link_to "ログアウト", public_logout_path, method: :delete, class: "nav-link text-white" %></li>
          <% else %>
            <li class="nav-item"><%= link_to "ユーザー登録", new_public_user_path, class: "nav-link text-white" %></li>
            <li class="nav-item"><%= link_to "ログイン", public_login_path, class: "nav-link text-white" %></li>
          <% end %>
        </ul>
      </div>
    </nav>
      <%= yield %>
  </body>
</html>